# Generated by Django 6.0.3 on 2026-03-10 21:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. temple, fort, museum', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('icon_url', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'categories',
                'indexes': [models.Index(fields=['name'], name='idx_categories_name')],
                'constraints': [models.UniqueConstraint(fields=('name',), name='uq_categories_name')],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('max_daily_capacity', models.IntegerField(help_text='Maximum visitors per day')),
                ('entry_fee_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_open', models.BooleanField(default=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('last_entry_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete — NULL means active', null=True)),
                ('category_id', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.RESTRICT, related_name='experiences', to='content.category')),
            ],
            options={
                'db_table': 'experience',
            },
        ),
        migrations.CreateModel(
            name='OperatingHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week', max_length=10)),
                ('opens_at', models.TimeField(blank=True, help_text='Opening time (NULL if closed)', null=True)),
                ('closes_at', models.TimeField(blank=True, help_text='Closing time (NULL if closed)', null=True)),
                ('is_closed', models.BooleanField(default=False, help_text='True if closed on this day')),
                ('special_closure_reason', models.CharField(blank=True, help_text='Reason for closure (e.g., Maintenance, Holiday)', max_length=255, null=True)),
                ('experience', models.ForeignKey(help_text='Monument/Experience these hours apply to', on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='content.experience')),
            ],
            options={
                'db_table': 'operating_hours',
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('senior', 'Senior')], help_text='Type of ticket (adult, child, senior)', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=2, help_text='Base price for this ticket type', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('seasonal_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='1.5 for peak season, 0.8 for off-season', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('valid_from', models.DateField(help_text='Start date for this pricing rule')),
                ('valid_to', models.DateField(blank=True, help_text='End date. NULL means ongoing', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience_id', models.ForeignKey(help_text='Monument/Experience this pricing applies to', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='content.experience')),
            ],
            options={
                'db_table': 'pricing_rules',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['category_id'], name='idx_experience_category_id'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['name'], name='idx_experience_name'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['category_id', 'is_open'], name='idx_category_is_open'),
        ),
        migrations.AddIndex(
            model_name='operatinghours',
            index=models.Index(fields=['experience'], name='operating_h_experie_db494d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operatinghours',
            unique_together={('experience', 'day_of_week')},
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['experience_id'], name='pricing_rul_experie_b1ed9e_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['experience_id', 'ticket_type', 'valid_from', 'valid_to'], name='pricing_composite_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together={('experience_id', 'ticket_type', 'valid_from', 'valid_to')},
        ),
    ]
