# Generated by Django 6.0.3 on 2026-04-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='experience',
            name='idx_experience_category_id',
        ),
        migrations.RemoveIndex(
            model_name='experience',
            name='idx_category_is_open',
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['category'], name='idx_experience_category'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['category', 'is_open'], name='idx_category_is_open'),
        ),
    ]
