# Generated by Django 6.0.3 on 2026-04-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_experience_idx_experience_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='public_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='location',
            name='public_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['public_id'], name='idx_experience_public_id'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['public_id'], name='idx_locations_public_id'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name'], name='idx_locations_name'),
        ),
    ]
