# Generated by Django 6.0.3 on 2026-06-07 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_experience_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('collection_type', models.CharField(choices=[('trail', 'Trail'), ('itinerary', 'Itinerary'), ('featured', 'Featured'), ('recommended', 'Recommended'), ('seasonal', 'Seasonal')], default='featured', max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete — NULL means active', null=True)),
            ],
            options={
                'db_table': 'collections',
            },
        ),
        migrations.CreateModel(
            name='CollectionExperience',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'collection_experiences',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete — NULL means active', null=True)),
            ],
            options={
                'db_table': 'provider',
            },
        ),
        migrations.CreateModel(
            name='TicketType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Soft delete — NULL means active', null=True)),
            ],
            options={
                'db_table': 'ticket_type',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('days', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'trips',
            },
        ),
        migrations.CreateModel(
            name='TripAttraction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day_number', models.IntegerField(default=1)),
                ('sequence', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trip_attractions',
                'ordering': ['day_number', 'sequence'],
            },
        ),
        migrations.RemoveIndex(
            model_name='pricingrule',
            name='pricing_rul_experie_86bb9f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricingrule',
            name='pricing_composite_idx',
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['public_id'], name='idx_collections_public_id'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['collection_type'], name='idx_collections_type'),
        ),
        migrations.AddIndex(
            model_name='collection',
            index=models.Index(fields=['is_active'], name='idx_collections_is_active'),
        ),
        migrations.AddField(
            model_name='collectionexperience',
            name='collection',
            field=models.ForeignKey(db_column='collection_id', on_delete=django.db.models.deletion.CASCADE, related_name='collection_experiences', to='content.collection'),
        ),
        migrations.AddField(
            model_name='collectionexperience',
            name='experience',
            field=models.ForeignKey(db_column='experience_id', on_delete=django.db.models.deletion.CASCADE, related_name='collection_experiences', to='content.experience'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['public_id'], name='idx_provider_public_id'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['name'], name='idx_provider_name'),
        ),
        migrations.AddIndex(
            model_name='provider',
            index=models.Index(fields=['is_active'], name='idx_provider_is_active'),
        ),
        migrations.AddField(
            model_name='experience',
            name='provider',
            field=models.ForeignKey(blank=True, db_column='provider_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiences', to='content.provider'),
        ),
        migrations.AddField(
            model_name='tickettype',
            name='experience',
            field=models.ForeignKey(db_column='experience_id', on_delete=django.db.models.deletion.CASCADE, related_name='ticket_types', to='content.experience'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='ticket_type',
            field=models.ForeignKey(blank=True, db_column='ticket_type_id', help_text='Ticket type this pricing applies to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='content.tickettype'),
        ),
        migrations.AlterUniqueTogether(
            name='pricingrule',
            unique_together={('ticket_type', 'valid_from', 'valid_to')},
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['ticket_type'], name='pricing_rul_ticket__bc1d88_idx'),
        ),
        migrations.AddIndex(
            model_name='pricingrule',
            index=models.Index(fields=['ticket_type', 'valid_from', 'valid_to'], name='pricing_composite_idx'),
        ),
        migrations.AddField(
            model_name='trip',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='content.location'),
        ),
        migrations.AddField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tripattraction',
            name='experience',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.experience'),
        ),
        migrations.AddField(
            model_name='tripattraction',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_attractions', to='content.trip'),
        ),
        migrations.AddIndex(
            model_name='collectionexperience',
            index=models.Index(fields=['collection'], name='idx_coll_exp_collection'),
        ),
        migrations.AddIndex(
            model_name='collectionexperience',
            index=models.Index(fields=['experience'], name='idx_coll_exp_experience'),
        ),
        migrations.AddIndex(
            model_name='collectionexperience',
            index=models.Index(fields=['display_order'], name='idx_coll_exp_display_order'),
        ),
        migrations.AddConstraint(
            model_name='collectionexperience',
            constraint=models.UniqueConstraint(fields=('collection', 'experience'), name='uq_collection_experience'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['public_id'], name='idx_ticket_type_public_id'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['experience'], name='idx_ticket_type_experience'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['name'], name='idx_ticket_type_name'),
        ),
        migrations.AddIndex(
            model_name='tickettype',
            index=models.Index(fields=['is_active'], name='idx_ticket_type_is_active'),
        ),
        migrations.AddConstraint(
            model_name='tickettype',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('experience', 'name'), name='uq_ticket_type_experience_name_active'),
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='experience',
        ),
        migrations.AlterUniqueTogether(
            name='tripattraction',
            unique_together={('trip', 'experience')},
        ),
    ]
