# Generated by Django 6.0.3 on 2026-03-10 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('booking_date', models.DateField(db_index=True)),
                ('slot_time', models.TimeField(blank=True, null=True)),
                ('total_tickets', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('used', 'Used')], db_index=True, default='pending', max_length=20)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refund_status', models.CharField(blank=True, choices=[('none', 'None'), ('requested', 'Requested'), ('processed', 'Processed'), ('failed', 'Failed')], default='none', max_length=20, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('experience_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='content.experience')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to='user.user_data')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(db_index=True, help_text='Transaction ID from payment gateway', max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Credit/Debit Card'), ('upi', 'UPI'), ('wallet', 'Digital Wallet'), ('bank_transfer', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('payment_gateway', models.CharField(blank=True, choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], help_text='Which payment gateway processed this', max_length=50, null=True)),
                ('gateway_transaction_id', models.CharField(blank=True, help_text='Transaction ID from the payment gateway', max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error details if payment failed', null=True)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When the payment was successfully processed', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='When the payment was refunded', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='user.user_data')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('adult', 'Adult'), ('child', 'Child'), ('senior', 'Senior')], help_text='Type of ticket (adult, child, senior)', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price paid for this ticket', max_digits=10)),
                ('qr_code', models.CharField(db_index=True, help_text='QR code for entry verification', max_length=255, unique=True)),
                ('is_used', models.BooleanField(db_index=True, default=False, help_text='Whether ticket has been used for entry')),
                ('used_at', models.DateTimeField(blank=True, help_text='When ticket was scanned/used', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_id', models.ForeignKey(help_text='Booking this ticket belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.booking')),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['experience_id', 'booking_date', 'status'], name='bookings_experie_d5311b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user_id', 'status'], name='payments_user_id_b89769_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='payments_created_e3a130_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['booking_id'], name='tickets_booking_968abe_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['qr_code'], name='tickets_qr_code_55047d_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['is_used'], name='tickets_is_used_d85731_idx'),
        ),
    ]
