# Generated by Django 6.0.3 on 2026-04-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('content', '0003_experience_public_id_location_public_id_and_more'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='booking',
            new_name='idx_booking_exp_date_status',
            old_name='bookings_experie_a7e11d_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='idx_payments_user_status',
            old_name='payments_user_id_1b771c_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='idx_payments_created_at',
            old_name='payments_created_e3a130_idx',
        ),
        migrations.AddField(
            model_name='booking',
            name='reference',
            field=models.CharField(db_index=True, default='defaultvalue', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='reference',
            field=models.CharField(db_index=True, default='defaultvalue', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference'], name='idx_booking_reference'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference'], name='idx_payments_reference'),
        ),
    ]
