# Generated by Django 6.0.3 on 2026-06-07 05:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('content', '0003_collection_collectionexperience_provider_tickettype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('public_id', models.CharField(blank=True, editable=False, max_length=15, unique=True)),
                ('inventory_date', models.DateField()),
                ('total_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('available_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('reserved_capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('is_closed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('experience', models.ForeignKey(db_column='experience_id', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='content.experience')),
            ],
            options={
                'db_table': 'inventory',
                'indexes': [models.Index(fields=['experience'], name='idx_inventory_experience'), models.Index(fields=['inventory_date'], name='idx_inventory_date'), models.Index(fields=['is_closed'], name='idx_inventory_is_closed')],
                'constraints': [models.UniqueConstraint(fields=('experience', 'inventory_date'), name='uq_experience_inventory_date')],
            },
        ),
    ]
