# Generated by Django 6.0.3 on 2026-03-21 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('user', '0002_alter_user_data_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_user_id_b89769_idx',
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['user_id', 'status'], name='payments_user_id_1b771c_idx'),
        ),
    ]
