# Generated by Django 6.0.3 on 2026-04-05 09:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_payment_booking_id_alter_ticket_booking_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='booking_reference',
            field=models.OneToOneField(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='booking.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='booking_id',
            field=models.ForeignKey(help_text='Booking this ticket belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='booking.booking'),
        ),
    ]
