# Generated by Django 6.0.3 on 2026-03-29 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_payment_payments_user_id_b89769_idx_and_more'),
        ('booking', '0003_alter_payment_booking_id_alter_ticket_booking_id'),
    ]

    operations = [
    ]
