# Generated by Django 6.0.3 on 2026-04-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_payment_payments_user_id_b89769_idx_and_more'),
        ('booking', '0005_alter_booking_user_id'),
    ]

    operations = [
    ]
